# Builds a final release version and pushes to nuget.org 
# whenever a release is published.
# Requires: secrets.NUGET_API_KEY

name: publish
on:
  release:
    types: [prereleased, released]

env:
  DOTNET_NOLOGO: true
  Configuration: Release
  PackageOutputPath: ${{ github.workspace }}/bin
  GeneratePackageOnBuild: true
  VersionLabel: ${{ github.ref }}
  
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: 🤘 checkout
        uses: actions/checkout@v4
        with: 
          submodules: recursive
          fetch-depth: 0

      - name: 🙏 build
        run: dotnet build

      - name: ⚙ install
        run: dotnet tool install -g dotnet-ilrepack --add-source bin

      - name: 🧪 test
        run: 
            ilrepack /help 
            if [ $? -eq 2 ]; then
                echo "Done"
            else
                exit 1
            fi        

      - name: 🚀 nuget
        run: dotnet nuget push ./bin/**/*.nupkg -s https://api.nuget.org/v3/index.json -k ${{secrets.NUGET_API_KEY}} --skip-duplicate
